# Generated by Django 4.2.15 on 2024-10-03 14:56

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker_voucher', '0006_alter_historicalworkervoucher_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkervoucher',
            name='assigned_date',
            field=core.fields.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalworkervoucher',
            name='expiry_date',
            field=core.fields.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workervoucher',
            name='assigned_date',
            field=core.fields.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workervoucher',
            name='expiry_date',
            field=core.fields.DateTimeField(blank=True, null=True),
        ),
    ]
