# Generated by Django 4.2.15 on 2024-10-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_voucher', '0008_workerupload_historicalworkerupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkerupload',
            name='status',
            field=models.CharField(choices=[('TRIGGERED', 'Triggered'), ('IN_PROGRESS', 'In progress'), ('SUCCESS', 'Success'), ('PARTIAL_SUCCESS', 'Partial success'), ('FAIL', 'Fail')], default='TRIGGERED', max_length=255),
        ),
        migrations.AlterField(
            model_name='workerupload',
            name='status',
            field=models.CharField(choices=[('TRIGGERED', 'Triggered'), ('IN_PROGRESS', 'In progress'), ('SUCCESS', 'Success'), ('PARTIAL_SUCCESS', 'Partial success'), ('FAIL', 'Fail')], default='TRIGGERED', max_length=255),
        ),
    ]
