# Generated by Django 4.2.15 on 2024-10-17 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policyholder', '0018_alter_historicalpolicyholder_date_created_and_more'),
        ('worker_voucher', '0011_historicalworkergroup_date_valid_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupofworker',
            name='policyholder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='policyholder.policyholder'),
        ),
        migrations.AddField(
            model_name='historicalgroupofworker',
            name='policyholder',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='policyholder.policyholder'),
        ),
    ]
