# Generated by Django 4.2.15 on 2024-10-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_voucher', '0012_groupofworker_policyholder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupofworker',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalgroupofworker',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
