# Generated by Django 4.2.15 on 2024-10-29 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worker_voucher', '0017_voucherformdraft_voucherformdraftworkersdetails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucherformdraft',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_voucher', to=settings.AUTH_USER_MODEL),
        ),
    ]
