# Generated by Django 4.2.16 on 2024-11-04 14:10

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker_voucher', '0018_alter_voucherformdraft_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkervoucher',
            name='date_of_assignment',
            field=core.fields.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workervoucher',
            name='date_of_assignment',
            field=core.fields.DateTimeField(blank=True, null=True),
        ),
    ]
