# Generated by Django 4.2.16 on 2024-11-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker_voucher', '0019_historicalworkervoucher_date_of_assignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkervoucher',
            name='status',
            field=models.CharField(blank=True, choices=[('AWAITING_PAYMENT', 'Awaiting Payment'), ('UNASSIGNED', 'Unassigned'), ('ASSIGNED', 'Assigned'), ('EXPIRED', 'Expired'), ('CANCELED', 'Canceled'), ('CLOSED', 'Closed'), ('PRINTED', 'Printed')], default='AWAITING_PAYMENT', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workervoucher',
            name='status',
            field=models.CharField(blank=True, choices=[('AWAITING_PAYMENT', 'Awaiting Payment'), ('UNASSIGNED', 'Unassigned'), ('ASSIGNED', 'Assigned'), ('EXPIRED', 'Expired'), ('CANCELED', 'Canceled'), ('CLOSED', 'Closed'), ('PRINTED', 'Printed')], default='AWAITING_PAYMENT', max_length=255, null=True),
        ),
    ]
